language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ext/ATCD/ACE
    - TAO_ROOT=$TRAVIS_BUILD_DIR/ext/ATCD/TAO
    - DDS_ROOT=$TRAVIS_BUILD_DIR
    - MPC_ROOT=$TRAVIS_BUILD_DIR/ext/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$DDS_ROOT/lib:$LD_LIBRARY_PATH

before_install:
  - mkdir ext
  - cd ext && git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone -b Latest_Beta --depth 1 git://github.com/DOCGroup/ATCD.git
  - cd ..

branches:
  only:
    - master

before_script:
  - export
  - echo -e "#include \"ace/config-linux.h\"" > $ACE_ROOT/ace/config.h
  - if [ "$CXX" == "g++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" > $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CXX" == "clang++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" > $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
#  - cat $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - cat $ACE_ROOT/ace/config.h
  - cat $ACE_ROOT/include/makeinclude/platform_macros.GNU

script:
  - tar czf modeling_plugins.tar.gz tools/modeling/plugins
  - rm -rf tools/modeling/plugins
  - perl $DDS_ROOT/tools/scripts/dds_fuzz.pl
  - tar xzf modeling_plugins.tar.gz
  - rm modeling_plugins.tar.gz
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace -workers 2 DDS_TAOv2_all.mwc
  - make -j2
  - cd tests/DCPS/Messenger && ./run_test.pl all
