install:
  - mkdir ext && cd ext
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone -b Latest_Beta --depth 1 git://github.com/DOCGroup/ATCD.git
  - cd ..
  - set MPC_ROOT=%CD%\ext\MPC
  - configure --no-tests --ace=ext\ATCD\ACE

platform:
  - x64

configuration:
  - Debug

build:
  project: DDS_TAOv2.sln

after_build:
  - cd DevGuideExamples\DCPS\Messenger && run_test.pl
