variables:
   system.prefergit: true

resources:
- repo: self
  fetchDepth: 1

jobs:
- job: VisualStudio2017
  timeoutInMinutes: 90
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: |
      $client = new-object System.Net.WebClient
      $client.DownloadFile("http://strawberryperl.com/download/5.28.0.1/strawberry-perl-5.28.0.1-64bit-portable.zip", "strawberry-perl.zip");
    displayName: Download perl
  - task: ExtractFiles@1
    displayName: Extract perl
    inputs:
      archiveFilePatterns: strawberry-perl.zip
      destinationFolder: ext\strawberry
  - script: git clone --depth 1 git://github.com/DOCGroup/MPC ext\MPC
    displayName: git clone MPC
  - script: git clone --depth 1 git://github.com/DOCGroup/ACE_TAO ext\ACE_TAO
    displayName: git clone ACE_TAO
  - task: BatchScript@1
    displayName: VcVars64
    inputs:
      filename: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
      modifyEnvironment: true
  - script: ext\strawberry\perl\bin\perl configure -v --ace=ext\ACE_TAO\ACE --mpc=ext\MPC
    displayName: Run configure script
  - task: BatchScript@1
    displayName: Setenv from configure script
    inputs:
      filename: setenv.cmd
      modifyEnvironment: true
  - task: VSBuild@1
    displayName: Build solution DDS_TAOv2_all.sln
    inputs:
      solution: DDS_TAOv2_all.sln
      platform: x64
      configuration: debug
      maximumCpuCount: true
