name: "Insert PR Number into News"

on:
  pull_request:
    paths:
      - 'docs/news.d/**'
    types: [opened, synchronize]

jobs:
  insert_news_pr_num:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenDDS
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}
    - name: Update PR
      run: python3 docs/news.py insert-pr-num ${{github.event.pull_request.number}}
