name: lint

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'

env:
  DDS_ROOT: ${{github.workspace}}
  DOC_ROOT: ${{github.workspace}}/ACE_TAO
  ACE_ROOT: ${{github.workspace}}/ACE_TAO/ACE
  TAO_ROOT: ${{github.workspace}}/ACE_TAO/TAO

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout OpenDDS
      uses: actions/checkout@v2
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
    - name: Run lint.pl
      run: |
        perl $DDS_ROOT/tools/scripts/lint.pl --simple-output
